<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Comparison of Integrity and Authenticity</title>
<style>
  body {
    font-family: Arial, sans-serif;
    line-height: 1.6;
    margin: 20px;
  }
  table {
    width: 100%;
    border-collapse: collapse;
  }
  th, td {
    border: 1px solid #000;
    padding: 8px;
    text-align: left;
  }
  th {
    background-color: #f2f2f2;
  }
  ul {
    margin: 0;
    padding: 0;
    list-style-type: none;
  }
  li {
    margin-bottom: 5px;
  }
  pre, code {
    background-color: #f4f4f4;
    display: block;
    padding: 8px;
  }
</style>
</head>
<body>

<h2>Comparison of Integrity and Authenticity</h2>

<table>
  <thead>
  <tr>
    <th>Aspect</th>
    <th>Integrity Check (Hash Verification)</th>
    <th>Authenticity Check (GPG Signature Verification)</th>
  </tr>
  </thead>
  <tbody>
  <tr>
    <td><strong>Definition</strong></td>
    <td>Ensures that the file’s hash (e.g., SHA-256) matches a reference hash, confirming that the file has not been modified during download or transfer.</td>
    <td>Verifies the file's origin and authenticity by checking its digital signature, ensuring it was signed with the publisher's **private key** and can be verified with their **public key**.</td>
  </tr>
  <tr>
    <td><strong>Purpose</strong></td>
    <td>Detects file corruption, accidental modifications, or unauthorized changes during transfer or storage.</td>
    <td>Confirms that the file is from the expected publisher and has not been tampered with, protecting against impersonation and malicious modifications.</td>
  </tr>
  <tr>
    <td><strong>Method</strong></td>
    <td>Generates a checksum (hash) of the downloaded file and compares it with an official hash (typically available on the publisher’s website).</td>
    <td>Uses GPG to verify the digital signature attached to the file, checking that the signature was created using the publisher's **private key** and matches the corresponding **public key**.</td>
  </tr>
  <tr>
    <td><strong>Commands</strong></td>
    <td><code>sha256sum file.img</code> (check the hash) and compare it with the official reference hash provided by the publisher.</td>
    <td><code>gpg --verify file.sig file.img</code> or <code>gpg --verify file.asc file.img</code> (verify the GPG signature using a pre-imported public key).</td>
  </tr>
  <tr>
    <td><strong>Protection Against</strong></td>
    <td>Data corruption, accidental file modifications, and integrity issues during download or storage.</td>
    <td>Malicious tampering, impersonation, and supply-chain attacks by verifying that the file was genuinely signed by the expected publisher.</td>
  </tr>
  <tr>
    <td><strong>Limitations</strong></td>
    <td>Does not provide any information about the source or creator of the file; it only checks for modifications to the file.</td>
    <td>Requires access to the publisher's **public key** and the ability to trust that key, meaning the key must already be imported and trusted in your GPG keyring.</td>
  </tr>
  <tr>
    <td><strong>File Types for Signature</strong></td>
    <td>Hash values are typically provided as plain text (e.g., SHA-256 sums).<br> These are not files you verify but are manually compared.</td>
    <td>Digital signatures are provided as `.sig` (binary format) or `.asc` (ASCII-armored format) files. These files contain the cryptographic signature for the corresponding file.</td>
  </tr>
  <tr>
    <td><strong>.sig vs .asc Files</strong></td>
    <td>Not applicable for integrity checks. Integrity checks rely on hash comparisons rather than signatures.</td>
    <td><ul>
    <li><strong>.sig</strong>: A binary format containing the cryptographic signature (used in automated systems).</li>
    <li><strong>.asc</strong>: An ASCII-armored, human-readable format of the same signature (suitable for text-based sharing or emails).</li>
    </ul></td>
  </tr>
  <tr>
    <td><strong>Key Concepts</strong></td>
    <td><ul>
    <li><strong>Hashing:</strong> A cryptographic function that generates a unique checksum of a file's contents, used for integrity verification.</li>
    </ul></td>
    <td><ul>
    <li><strong>Public Key:</strong> A key used to verify signatures. It is publicly available and used to ensure that the file was signed with the corresponding private key.</li>
    <li><strong>Private Key:</strong> A secret key used to create the signature. It is kept confidential by the publisher.</li>
    <li><strong>Signature:</strong> A cryptographic value generated by the private key, proving that the file was signed by the publisher and has not been altered.</li>
    </ul></td>
  </tr>
  <tr>
    <td><strong>Example Usage</strong></td>
    <td><pre><code>sha256sum tails.img</code></pre> (compare this output with the official hash on the website).</td>
    <td><pre><code>gpg --verify tails-amd64-6.9.img.sig tails-amd64-6.9.img</code></pre> (verify the signature of the file against the publisher's public key).</td>
  </tr>
  </tbody>
</table>

</body>
</html>
